691080451737124935:
  adminrole: null
  blacklist: []
  commandprefix: '&'
  google: true
  mal: true
  safesearch: false
  scholar: true
  sudoer: []
  wikipedia: true
  xkcd: true
  youtube: true
757210257184260157:
  adminrole: null
  blacklist: []
  commandprefix: '&'
  google: true
  mal: true
  safesearch: false
  scholar: true
  sudoer: []
  wikipedia: true
  xkcd: true
  youtube: true
758004308233945186:
  adminrole: null
  blacklist: []
  commandprefix: '&'
  google: true
  mal: true
  safesearch: false
  scholar: true
  sudoer: []
  wikipedia: true
  xkcd: true
  youtube: true
774104445348478976:
  adminrole: null
  blacklist: []
  commandprefix: '&'
  google: true
  mal: true
  safesearch: false
  scholar: true
  sudoer: []
  wikipedia: true
  xkcd: true
  youtube: true
801170004179157033:
  adminrole: null
  blacklist: []
  commandprefix: '&'
  google: true
  mal: true
  safesearch: false
  scholar: true
  sudoer: []
  wikipedia: true
  xkcd: true
  youtube: true
